version: '3.8'

services:
  demo-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    volumes:
      - ./build/db:/desktop_app/build/db
    environment:
      - JAVA_OPTS=-Xmx1g -XX:MaxMetaspaceSize=1024m

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:h2:mem:sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: