name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

  pull_request_target:
    types: [closed]

jobs:
  build-test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image (Test)
        run: |
          docker build -t mattmcdou/ci-cd-test-image .

  push-image:
    name: Push Docker Image on Merge
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --no-cache -t mattmcdou/ci-cd-pipeline-automation-app:latest .

      - name: Tag & Push Versioned Image
        run: |
          VERSION=$(git rev-parse --short HEAD)
          docker tag mattmcdou/ci-cd-pipeline-automation-app:latest mattmcdou/ci-cd-pipeline-automation-app:$VERSION
          docker push mattmcdou/ci-cd-pipeline-automation-app:$VERSION

      - name: Push Latest Image
        run: |
          docker push mattmcdou/ci-cd-pipeline-automation-app:latest

